[project]
name = "simple-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-mcp-adapters>=0.1.12",
    "langchain[openai]>=1.0.5",
    "langgraph>=1.0.3",
    "python-dotenv>=1.2.1",
]
